export const GET_CATEGORY = 'GET_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';

export const GET_FLASHCARD_LIST = 'GET_FLASHCARD_LIST';
export const ADD_FLASHCARD = 'ADD_FLASHCARD';

export const GET_FLASHCARD_TO_LEARN = 'GET_FLASHCARD_TO_LEARN';
export const MARK_AS_KNOWN = 'MARK_AS_KNOWN';